version: '3.5'

services: 
  app_todo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jojo1234
      PG_HOST: db
      POSTGRES_PORT: 5432
      SECRET_KEY: django-insecure-l6aw$vcwr7k4ec=ktk7yv^zu^-egkq9*!d0r7-1g3dxasi-s$e
      DEBUG: True
    volumes:
      - shared-volume:/app/src/static
      - staticfiles:/app/staticfiles 
    depends_on:
      - db
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - shared-volume:/app/src/static
    depends_on:
      - app_todo
  db: 
    image: postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres

volumes:
  shared-volume:
  staticfiles: