# Generated by Django 4.2.13 on 2024-05-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE todo (
                todo_id SERIAL PRIMARY KEY,
                user_id int NOT NULL,
                title varchar(255) NOT NULL,
                description text,
                status varchar(50) NOT NULL,
                due_date timestamp,
                created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (user_id) REFERENCES "users" (user_id)
            );
            """,
            reverse_sql="DROP TABLE todo;"
        )
    ]
