# Generated by Django 4.2.13 on 2024-05-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_adding_fk'),
        ('todos', '0003_adding_table'),
    ]

    operations = [
    ]
