# Generated by Django 4.2.13 on 2024-06-01 09:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
           ('todos', '0004_merge_0002_adding_fk_0003_adding_table'),  # Correct the dependency
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE todo
            DROP COLUMN status,
            DROP COLUMN due_date;
            """,
            reverse_sql="""
            ALTER TABLE todo
            ADD COLUMN status varchar(50),
            ADD COLUMN due_date timestamp;
            """
        )
    ]
