# Generated by Django 4.2.13 on 2024-06-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_adding_table_usage'),
        ('todos', '0006_remove_column'),
    ]

    operations = [
    ]
