# Generated by Django 4.2.13 on 2024-06-08 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('todos', '0005_adding_table_usage'),
        # ('todos', '0006_remove_column'),
        # ('todos', '0007_merge_0005_adding_table_usage_0006_remove_column'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE todo
            ADD COLUMN accomplished BOOLEAN DEFAULT FALSE
            """,
            reverse_sql="""
            ALTER TABLE todo
            DROP COLUMN IF EXISTS accomplished;
            """
        )
    ]
