# Generated by Django 4.2.13 on 2024-06-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_merge_0005_adding_table_usage_0006_remove_column'),
        ('todos', '0008_adding_column_accomplished'),
    ]

    operations = [
    ]
