# Generated by Django 4.2.13 on 2024-05-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initiate'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE profile (
                profile_id SERIAL PRIMARY KEY,
                user_id INT NOT NULL,
                first_name VARCHAR(255),
                last_name VARCHAR(255),
                bio TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (user_id) REFERENCES users (user_id)
            );
            """,
            reverse_sql="DROP TABLE profile;"
        )
    ]
